#!/usr/bin/env bash
#
# Prepare the bind-mount sources for the e2e slice (docker-compose.e2e.yml).
# Idempotent; safe on a fresh CI checkout and on a dev machine (touches ONLY ./.e2e).
#
#   scripts/e2e-ci-prepare.sh           # create ./.e2e/* if missing
#   scripts/e2e-ci-prepare.sh --fresh   # also wipe per-run state (bridge store,
#                                       # notifier cursor, output) for determinism
#
# Why this exists: three of the compose mounts are *files*. If a source file is
# missing, Docker silently creates a directory at that path and the app breaks at
# runtime in confusing ways. Two of those (resume.yaml, candidate_profile.yaml)
# are committed fixtures mounted directly by the override; the third — the
# pipeline dotenv — is generated here because it embeds the markserv port.
# ARTIFACT_BASE_URL must live in this dotenv, NOT in compose environment: an
# empty compose var would beat the mounted file (Config.get precedence) and
# AddArtifactUrlNode would silently no-op.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

E2E_DIR=".e2e"
MARKSERV_PORT="${E2E_MARKSERV_PORT:-18081}"

if [ "${1:-}" = "--fresh" ]; then
  echo "[e2e-prepare] wiping per-run state under $E2E_DIR/"
  rm -rf "$E2E_DIR/bridge-store" "$E2E_DIR/notifier-state" "$E2E_DIR/output"
fi

mkdir -p "$E2E_DIR/output" "$E2E_DIR/state" "$E2E_DIR/bridge-store" "$E2E_DIR/notifier-state"

cat > "$E2E_DIR/pipeline.env" <<EOF
# Generated by scripts/e2e-ci-prepare.sh — mounted at /app/.env in the e2e processor.
ARTIFACT_BASE_URL=http://127.0.0.1:${MARKSERV_PORT}
EOF

# Fail fast if the committed fixture files the override bind-mounts are missing —
# otherwise Docker would create directories in their place inside the container.
for f in services/job-fit-apply-ai-e2e/fixtures/resume.yaml \
         services/job-fit-apply-ai-e2e/fixtures/candidate_profile.yaml; do
  [ -f "$f" ] || { echo "[e2e-prepare] missing fixture: $f" >&2; exit 1; }
done

echo "[e2e-prepare] ready: $E2E_DIR/ (markserv port $MARKSERV_PORT)"
